/**********
 * Retrieves the lock object from a restraint, if it exists. 
 * 
 * - (restraint object) restraint - The restraint to test for
 * ---
 * ##### Returns a lock object if it exists. All lock objects have the following properties:
 * - type: The item ID of the lock
 * - uuid: Unique ID of the lock, generated by crypto.randomUUID();
 * - keyholder: The keyholder of the lock. Defaults to the person who put it on
 * - clonedkeyholder: Any secondary keyholders 
 * ##### ... May have additional properties depending on lock parameters
 **********/
function getRestraintLock(restraint) {
    return restraint?.lock;
}

exports.getRestraintLock = getRestraintLock;