const honorifictitles = [
    // Oh god its hard to type these without caps
    "miss",
    "master",
    "masters",
    "sir",
    "sirs",
    "ma\'am",
    "maam",
    "lady",
    "ladies",
    "lord",
    "lords",
    "queen",
    "queens",
    "king",
    "kings",
    "mistress",
    "mistresses",
    "goddess",
    "goddesses",
    "maitresse",
    "administrator",
    "administrators",
    "mommy",
    "mommies",
    "daddy",
    "daddies",
    "mxtress",
    "overseer",
    "headmaid",
    "head\ maid",
    "mx",
    "duke",
    "dukes",
    "dame",
    "count",
    "overlord",
    "(\\w|\\d)+-sama",
    "(\\w|\\d)+-sensei",
    "(\\w|\\d)+-san",
    "(\\w|\\d)+-senpai",
];

exports.honorifictitles = honorifictitles;